### ISSUE TITLE
False errors on Char literals

### ISSUE THREAD

**Issue by chekoopa** [intellij-purescript/intellij-purescript#3] opened 2019-05-31 08:09 UTC
Strings are obvious, but characters are being used too, but not supported by the plugin (besides of requiring a version patch).

To reproduce it, here's an example of code, which fail the syntax check at now:

```purescript
fixDot :: String -> String
fixDot = charMap (\x -> if x == '.' then ',' else x)
```

**Comment by Neppord** [comment] 2021-02-05 21:50
I close this one since it is old and have not seen any activity. Please shout if it can be reproduced and should be reopen.

**Closed by Neppord** 2021-02-05 21:50 UTC
Labels: help wanted
